name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'bot_service/**/*'
      - 'Dockerfile'

env:
  PROJECT_ID: mipt-hack-01
  GAR_LOCATION: us-central1
  SERVICE: city-bot
  REGION: us-central1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run/${{ env.SERVICE }}:${{ github.sha }}" ./
          gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev"
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run/${{ env.SERVICE }}:${{ github.sha }}
          flags: '--allow-unauthenticated'
          secrets: |
            TELEGRAM_TOKEN=telegram-token:latest

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

